# Generated by Django 2.2.28 on 2023-05-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='label',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
